django_todo/urls.py
from django.contrib import admin
from django.urls import path
from todo import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.get_todo_list, name='get_todo_list'),
    path('add', views.add_item, name='add'),
    path('edit/<item_id>', views.edit_item, name='edit'),
    path('toggle/<item_id>', views.toggle_item, name='toggle'),
    path('delete/<item_id>', views.delete_item, name='delete'),
]

todo/models.py
from django.db import models

# Create your models here.


class Item(models.Model):
    name = models.CharField(max_length=50, null=False, blank=False)
    done = models.BooleanField(null=False, blank=False, default=False)

    def __str__(self):
        return self.name

todo/forms.py
from django import forms
from .models import Item


class ItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = ['name', 'done']

todo/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Item
from .forms import ItemForm

# Create your views here.


def get_todo_list(request):
    items = Item.objects.all()
    context = {
        'items': items
    }
    return render(request, 'todo/todo_list.html', context)


def add_item(request):
    if request.method == "POST":
        form = ItemForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('get_todo_list')
    form = ItemForm()
    context = {
        'form': form
    }

    return render(request, 'todo/add_item.html', context)


def edit_item(request, item_id):
    item = get_object_or_404(Item, id=item_id)
    if request.method == "POST":
        form = ItemForm(request.POST, instance=item)
        if form.is_valid():
            form.save()
            return redirect('get_todo_list')
    form = ItemForm(instance=item)
    context = {
        'form': form
    }
    return render(request, 'todo/edit_item.html', context)


def toggle_item(request, item_id):
    item = get_object_or_404(Item, id=item_id)
    item.done = not item.done
    item.save()
    return redirect('get_todo_list')


def delete_item(request, item_id):
    item = get_object_or_404(Item, id=item_id)
    item.delete()
    return redirect('get_todo_list')

todo/templates/todo/add_item.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>Add a Todo Item</h1>

    <form method="POST" action="add">
        {% csrf_token %}
        <div>
            <p>
                <label for="id_name">Name: </label>
                <input type="text" id="id_name" name="item_name" />
            </p>
        </div>
        <div>
            <p>
                <label for="id_done">Done: </label>
                <input type="checkbox" id="id_done" name="done" />
            </p>
        </div>
        <div>
            <p>
                <button type="submit">Add Item</button>
            </p>
        </div>
    </form>
    
</body>
</html>

todo/templates/todo/edit_item.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>Edit a Todo Item</h1>

    <form method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <div>
            <p>
                <button type="submit">Update Item</button>
            </p>
        </div>
    </form>
    
</body>
</html>

todo/templates/todo/todo_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>Things I need to do:</h1>
    <table>
        {% for item in items %}
    <tr>
        {% if item.done %}
            <td><strike>{{ item.name }}</strike></td>
        {% else %}
            <td>{{ item.name }}</td>
        {% endif %}
        <td>
            <a href="/toggle/{{ item.id }}">
                <button>Toggle</button>
            </a>
        </td>
            <td>
                <a href="/edit/{{ item.id }}">
                    <button>Edit</button>
                </a>
            </td>
            <td>
                <a href="/delete/{{ item.id }}">
                    <button>Delete</button>
                </a>
            </td>
    </tr>
        {% empty %}
            <tr><td>You have nothing to do</td></tr>
        {% endfor %}
    </table>
        <a href="/add">Add an Item</a>
</body>
</html>